In [2]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder

In [3]:
df=pd.read_excel("../data/raw/Telco_customer_churn.xlsx")

In [4]:
df.drop(columns=['CustomerID',
                 'City',
                 'Zip Code',
                'Count',
                'Country',
                'State',
                'Lat Long',
                'Churn Label',
                'Churn Score',
                'Churn Reason'],
                   inplace=True)

In [5]:
list(df.columns)

['Latitude',
 'Longitude',
 'Gender',
 'Senior Citizen',
 'Partner',
 'Dependents',
 'Tenure Months',
 'Phone Service',
 'Multiple Lines',
 'Internet Service',
 'Online Security',
 'Online Backup',
 'Device Protection',
 'Tech Support',
 'Streaming TV',
 'Streaming Movies',
 'Contract',
 'Paperless Billing',
 'Payment Method',
 'Monthly Charges',
 'Total Charges',
 'Churn Value',
 'CLTV']

In [6]:
df['Total Charges'].dtype

dtype('O')

In [7]:
df[df['Total Charges'].isin([" ",""])]['Total Charges'].count()

np.int64(11)

In [8]:
df[df['Total Charges'].isin([" ",""])][['Tenure Months','Monthly Charges','Total Charges']]

      Tenure Months  Monthly Charges Total Charges
2234              0            52.55
2438              0            20.25
2568              0            80.85
2667              0            25.75
2856              0            56.05
4331              0            19.85
4687              0            25.35
5104              0            20.00
5719              0            19.70
6772              0            73.35
6840              0            61.90

In [9]:
df.loc[df['Total Charges'].isin([" ",""]),"Total Charges"]=np.nan

In [10]:
df['Total Charges'].isna().sum()

np.int64(11)

In [11]:
df['Total Charges'].dtype

dtype('O')

In [12]:
df['Total Charges']=pd.to_numeric(df['Total Charges'])

In [13]:
df.loc[
    df['Total Charges'].isna(),
['Tenure Months','Monthly Charges','Total Charges','Churn Value']]

      Tenure Months  Monthly Charges  Total Charges  Churn Value
2234              0            52.55            NaN            0
2438              0            20.25            NaN            0
2568              0            80.85            NaN            0
2667              0            25.75            NaN            0
2856              0            56.05            NaN            0
4331              0            19.85            NaN            0
4687              0            25.35            NaN            0
5104              0            20.00            NaN            0
5719              0            19.70            NaN            0
6772              0            73.35            NaN            0
6840              0            61.90            NaN            0

In [14]:
df.fillna({'Total Charges':0},inplace=True)

,Latitude,Longitude,Gender,Senior Citizen,Partner,Dependents,Tenure Months,Phone Service,Multiple Lines,Internet Service,...,Tech Support,Streaming TV,Streaming Movies,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Value,CLTV
0,33.964131,-118.272783,Male,No,No,No,2,Yes,No,DSL,...,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,1,3239
1,34.059281,-118.307420,Female,No,No,Yes,2,Yes,No,Fiber optic,...,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,1,2701
2,34.048013,-118.293953,Female,No,No,Yes,8,Yes,Yes,Fiber optic,...,No,Yes,Yes,Month-to-month,Yes,Electronic check,99.65,820.50,1,5372
3,34.062125,-118.315709,Female,No,Yes,Yes,28,Yes,Yes,Fiber optic,...,Yes,Yes,Yes,Month-to-month,Yes,Electronic check,104.80,3046.05,1,5003
4,34.039224,-118.266293,Male,No,No,Yes,49,Yes,Yes,Fiber optic,...,No,Yes,Yes,Month-to-month,Yes,Bank transfer (automatic),103.70,5036.30,1,5340
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,34.341737,-116.539416,Female,No,No,No,72,Yes,No,No,...,No internet service,No internet service,No internet service,Two year,Yes,Bank transfer (automatic),21.15,1419.40,0,5306
7039,34.667815,-117.536183,Male,No,Yes,Yes,24,Yes,Yes,DSL,...,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.50,0,2140
7040,34.559882,-115.637164,Female,No,Yes,Yes,72,Yes,Yes,Fiber optic,...,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.90,0,5560
7041,34.167800,-116.864330,Female,No,Yes,Yes,11,No,No phone service,DSL,...,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,0,2793
7042,34.424926,-117.184503,Male,No,No,No,66,Yes,No,Fiber optic,...,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.50,0,5097

In [15]:
df['Total Charges'].isna().sum()

np.int64(0)

In [16]:
df['total charges aggregated']=df['Monthly Charges']*df['Tenure Months']

In [17]:
df['total charges aggregated']-df['Total Charges']

0        -0.45
1       -10.25
2       -23.30
3      -111.65
4        45.00
         ...
7038    103.40
7039     44.70
7040     67.50
7041    -20.85
7042    128.40
Length: 7043, dtype: float64

In [18]:
(df['total charges aggregated']-df['Total Charges']).mean()

np.float64(-0.15295328695158086)

In [19]:
df.drop(columns=['total charges aggregated','Total Charges'],inplace=True)

In [20]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 22 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Latitude           7043 non-null   float64
 1   Longitude          7043 non-null   float64
 2   Gender             7043 non-null   str
 3   Senior Citizen     7043 non-null   str
 4   Partner            7043 non-null   str
 5   Dependents         7043 non-null   str
 6   Tenure Months      7043 non-null   int64
 7   Phone Service      7043 non-null   str
 8   Multiple Lines     7043 non-null   str
 9   Internet Service   7043 non-null   str
 10  Online Security    7043 non-null   str
 11  Online Backup      7043 non-null   str
 12  Device Protection  7043 non-null   str
 13  Tech Support       7043 non-null   str
 14  Streaming TV       7043 non-null   str
 15  Streaming Movies   7043 non-null   str
 16  Contract           7043 non-null   str
 17  Paperless Billing  7043 non-null   str
 18  Payment Method     7043 non-null   str
 19  Monthly Charges    7043 non-null   float64
 20  Churn Value        7043 non-null   int64
 21  CLTV               7043 non-null   int64
dtypes: float64(3), int64(3), str(16)
memory usage: 1.2 MB

In [21]:
df['Gender'].unique()

<StringArray>
['Male', 'Female']
Length: 2, dtype: str

In [22]:
df['Gender']=df['Gender'].map({'Female':1,'Male':0})

In [23]:
df['Gender'].unique()

array([0, 1])

In [24]:
df['Senior Citizen'].unique()

<StringArray>
['No', 'Yes']
Length: 2, dtype: str

In [25]:
df['Partner'].unique()

<StringArray>
['No', 'Yes']
Length: 2, dtype: str

In [26]:
df['Dependents'].unique()

<StringArray>
['No', 'Yes']
Length: 2, dtype: str

In [27]:
df['Phone Service'].unique()

<StringArray>
['Yes', 'No']
Length: 2, dtype: str

In [28]:
df['Multiple Lines'].unique()

<StringArray>
['No', 'Yes', 'No phone service']
Length: 3, dtype: str

In [29]:
df['Multiple Lines']=df['Multiple Lines'].replace({"No phone service":"No"})

In [30]:
df['Multiple Lines'].unique()

<StringArray>
['No', 'Yes']
Length: 2, dtype: str

In [31]:
df['Internet Service'].unique()

<StringArray>
['DSL', 'Fiber optic', 'No']
Length: 3, dtype: str

In [32]:
df['Online Security'].unique()

<StringArray>
['Yes', 'No', 'No internet service']
Length: 3, dtype: str

In [33]:
df['Online Backup'].unique()

<StringArray>
['Yes', 'No', 'No internet service']
Length: 3, dtype: str

In [34]:
df['Device Protection'].unique()

<StringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str

In [35]:
df['Tech Support'].unique()

<StringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str

In [36]:
df['Streaming TV'].unique()

<StringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str

In [37]:
df['Streaming Movies'].unique()

<StringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str

In [38]:
service_columns=[
    'Online Security', 'Online Backup', 'Device Protection', 
    'Tech Support', 'Streaming TV', 'Streaming Movies'
]

In [39]:
for column in service_columns:
    df[column]=df[column].replace({"No internet service":"No"})

In [40]:
for column in service_columns:
    print(column, df[column].unique())

Online Security <StringArray>
['Yes', 'No']
Length: 2, dtype: str
Online Backup <StringArray>
['Yes', 'No']
Length: 2, dtype: str
Device Protection <StringArray>
['No', 'Yes']
Length: 2, dtype: str
Tech Support <StringArray>
['No', 'Yes']
Length: 2, dtype: str
Streaming TV <StringArray>
['No', 'Yes']
Length: 2, dtype: str
Streaming Movies <StringArray>
['No', 'Yes']
Length: 2, dtype: str

In [41]:
df['Paperless Billing'].unique()

<StringArray>
['Yes', 'No']
Length: 2, dtype: str

In [42]:
df['Contract'].unique()

<StringArray>
['Month-to-month', 'Two year', 'One year']
Length: 3, dtype: str

In [43]:
contract_mapping={'Month-to-month':0,
                    'One year':1,
                    'Two year':2}

In [44]:
df['Contract']=df['Contract'].map(contract_mapping)

In [45]:
df['Payment Method'].unique()

<StringArray>
[             'Mailed check',          'Electronic check',
 'Bank transfer (automatic)',   'Credit card (automatic)']
Length: 4, dtype: str

In [46]:
yes_no_colums=['Senior Citizen','Partner','Dependents','Phone Service','Multiple Lines','Online Security', 'Online Backup', 'Device Protection', 
    'Tech Support', 'Streaming TV', 'Streaming Movies','Paperless Billing']

In [47]:
for column in yes_no_colums:
    df[column]=df[column].map({'Yes':1,"No":0})

In [48]:
for column in yes_no_colums:
    print(column, df[column].unique())

Senior Citizen [0 1]
Partner [0 1]
Dependents [0 1]
Phone Service [1 0]
Multiple Lines [0 1]
Online Security [1 0]
Online Backup [1 0]
Device Protection [0 1]
Tech Support [0 1]
Streaming TV [0 1]
Streaming Movies [0 1]
Paperless Billing [1 0]

In [49]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 22 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Latitude           7043 non-null   float64
 1   Longitude          7043 non-null   float64
 2   Gender             7043 non-null   int64
 3   Senior Citizen     7043 non-null   int64
 4   Partner            7043 non-null   int64
 5   Dependents         7043 non-null   int64
 6   Tenure Months      7043 non-null   int64
 7   Phone Service      7043 non-null   int64
 8   Multiple Lines     7043 non-null   int64
 9   Internet Service   7043 non-null   str
 10  Online Security    7043 non-null   int64
 11  Online Backup      7043 non-null   int64
 12  Device Protection  7043 non-null   int64
 13  Tech Support       7043 non-null   int64
 14  Streaming TV       7043 non-null   int64
 15  Streaming Movies   7043 non-null   int64
 16  Contract           7043 non-null   int64
 17  Paperless Billing  7043 non-null   int64
 18  Payment Method     7043 non-null   str
 19  Monthly Charges    7043 non-null   float64
 20  Churn Value        7043 non-null   int64
 21  CLTV               7043 non-null   int64
dtypes: float64(3), int64(17), str(2)
memory usage: 1.2 MB

In [51]:
df.to_csv("../data/processed/telco_cleaned_base.csv")